#!/bin/bash
# deploy.sh
# Prompts for config values, generates bin/config.ts, then runs cdk deploy
#
# Usage:
#   chmod +x scripts/deploy.sh
#   ./scripts/deploy.sh

set -e

echo ""
echo "╔══════════════════════════════════════╗"
echo "║       Amplify CDK Infra Deploy       ║"
echo "╚══════════════════════════════════════╝"
echo ""
echo "  Enter your configuration values below."
echo "  These will be used to name your AWS resources."
echo ""

# ── Prompt for values ─────────────────────────────────────────────────────────

read -p "  Your ID/username — used as bucket name prefix (e.g. johndoe): " ID
if [[ -z "$ID" ]]; then
  echo "❌  ID cannot be empty."
  exit 1
fi
# S3 bucket names must be lowercase
ID=$(echo "$ID" | tr '[:upper:]' '[:lower:]')
echo "  ℹ️  ID will be used as: $ID (lowercased for S3 compatibility)"

read -p "  AWS region (default: us-east-1): " AWS_REGION
AWS_REGION=${AWS_REGION:-us-east-1}

read -p "  Cognito User Pool name (default: ${ID}-app-users): " USER_POOL_NAME
USER_POOL_NAME=${USER_POOL_NAME:-${ID}-app-users}

read -p "  From email for Cognito invites (e.g. noreply@yourdomain.com): " FROM_EMAIL
if [[ -z "$FROM_EMAIL" ]]; then
  echo "❌  From email cannot be empty."
  exit 1
fi

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo "  ────────────────────────────────────────"
echo "  ID:            $ID"
echo "  Region:        $AWS_REGION"
echo "  User Pool:     $USER_POOL_NAME"
echo "  From Email:    $FROM_EMAIL"
echo "  ────────────────────────────────────────"
echo ""
read -p "  Proceed with deploy? (y/n): " CONFIRM
if [[ "$CONFIRM" != "y" && "$CONFIRM" != "Y" ]]; then
  echo "  Cancelled."
  exit 0
fi

# ── Generate bin/config.ts ────────────────────────────────────────────────────

echo ""
echo "  Generating bin/config.ts ..."

cat > bin/config.ts << EOF
// Auto-generated by scripts/deploy.sh — do not edit manually
// Run scripts/deploy.sh again to redeploy with new values

export const config = {
  id:           "${ID}",
  awsRegion:    "${AWS_REGION}",
  userPoolName: "${USER_POOL_NAME}",
  fromEmail:    "${FROM_EMAIL}",
};
EOF

echo "  ✅ bin/config.ts generated"
echo ""

# ── Install dependencies if needed ───────────────────────────────────────────

if [ ! -d "node_modules" ]; then
  echo "  Installing dependencies..."
  npm install
  echo ""
fi

# ── Deploy ────────────────────────────────────────────────────────────────────

echo "  Running cdk deploy ..."
echo ""
npx cdk deploy

# ── Verify ────────────────────────────────────────────────────────────────────

echo ""
echo "  Verifying deployment ..."
echo ""
bash scripts/check-stack.sh
